from selenium.webdriver.common.by import By


class MainPageLocators(object):
    MainText = (By.CSS_SELECTOR, '.component-content > .field-promotext > p')
    Subtext1 = (By.CSS_SELECTOR, '.component:nth-child(6) .promo-image-left__header')
    PlusButton = (By.LINK_TEXT, '+')
    BenefitsOption1 = (By.CSS_SELECTOR , '.modal-content > #benefits-tags > .tag:nth-child(1) > a')
    BenefitsOption2 = (By.CSS_SELECTOR, '.modal-content > #benefits-tags > .tag:nth-child(4) > a')
    BenefitsOption3 = (By.CSS_SELECTOR, '.modal-content > #benefits-tags > .tag:nth-child(7) > a')
    CloseButtonBenefits = (By.CSS_SELECTOR, '#benefits-tags-modal .close')
    CloseButtonApplications = (By.CSS_SELECTOR, '#applications-tags-modal .close')
    ApplicationsOption1 = (By.CSS_SELECTOR, '#applications > .tag:nth-child(1) > a')
    ApplicationsOption2 = (By.CSS_SELECTOR, '#applications > .tag:nth-child(4) > a')
    ApplicationsPlus = (By.CSS_SELECTOR, '#applications-button > .button')
    MetalPlus = (By.CSS_SELECTOR, '#metals-button > .button')
    MetalOption1 = (By.CSS_SELECTOR, '#metals > .tag:nth-child(1) > a')
    MetalOption2 = (By.CSS_SELECTOR, '#metals > .tag:nth-child(10) > a')
    CloseButtonMetal = (By.CSS_SELECTOR, '#metals-tags-modal .close')
    ShowResults = (By.ID, 'btn-results')
    MoreClads = (By.ID, 'spanNumberInitialPCladResults')
    MorePublications = (By.ID, 'spanNumberInitialPubResults')
    GetStarted = (By.LINK_TEXT, 'GET STARTED')
    Metal1 = (By.ID, 'metal-one')
    Option1 = (By.XPATH, "//option[. = 'Carbon Steel']")
    Metal2 = (By.ID, '00N3s00000PIirx')
    Option2 = (By.XPATH, "//option[. = 'Steel']")
    Submit = (By.ID, "metals-submit")
    CladResult = (By.CSS_SELECTOR, '.resource-search-result__resource-name')
    LearnMore = (By.LINK_TEXT, 'LEARN MORE')
    LMText1 = (By.CSS_SELECTOR, '.page-copy > p:nth-child(3)')
    LMText2 = (By.CSS_SELECTOR, 'p:nth-child(16)')
    LMText3 = (By.CSS_SELECTOR, 'p:nth-child(26)')
    Explore = (By.LINK_TEXT, 'EXPLORE THIS SERVICE')
    WatchVideo = (By.LINK_TEXT, 'WATCH THE VIDEO')
    DetaClad = (By.LINK_TEXT, 'WHY DETACLAD WORKS')
    CookieButton = (By.CSS_SELECTOR, '.submit > a')
    Home = (By.CSS_SELECTOR, '.nav-logo-white')
    LetsTalk = (By.LINK_TEXT, "LET'S TALK")
    FirstName = (By.ID, 'first_name')
    TextArea = (By.CSS_SELECTOR, 'textarea')
    SearchButton = (By.CSS_SELECTOR, '.navigation-main-search-icon > svg')
    SearchArea = (By.NAME, 'textBoxSearch')
    SearchResult = (By.CSS_SELECTOR, 'li:nth-child(1) .resource-search-result__resource-name')
    EmailField = (By.ID, 'fieldEmail')
    SubmitEmail = (By.CSS_SELECTOR, '.mailing-list-button')
    Confirmation = (By.CSS_SELECTOR, 'p')


class WeldingTechniquesLocators(object):
    Intro = (By.CSS_SELECTOR, '.page-intro > p')
    Image1 = (By.CSS_SELECTOR, '.col-3:nth-child(2) .image-caption-bar__image > img')
    Image2 = (By.CSS_SELECTOR, '.col-3:nth-child(3) .image-caption-bar__image > img')
    Image3 = (By.CSS_SELECTOR, '.col-3:nth-child(4) .image-caption-bar__image > img')
    Image4 = (By.CSS_SELECTOR, '.col-3:nth-child(3) .border-top-brand img')
    Link1 = (By.LINK_TEXT, 'LEARN MORE')
    Link1Text1 = (By.CSS_SELECTOR, 'p:nth-child(2)')
    Link1Text2 = (By.CSS_SELECTOR, 'p:nth-child(4)')
    Link1Image1 = (By.CSS_SELECTOR, '.component:nth-child(4) img')
    Link1Image2 = (By.CSS_SELECTOR, '.col-6:nth-child(2) .field-promoicon2 > img')
    Link1Image3 = (By.CSS_SELECTOR, '.col-6:nth-child(4) .field-promoicon2 > img')
    Link1Image4 = (By.CSS_SELECTOR, '.col-6:nth-child(5) .field-promoicon2 > img')
    Link2 = (By.LINK_TEXT, 'READ MORE')
    Link2Text1 = (By.CSS_SELECTOR, '.page-copy > p:nth-child(1)')
    Link2Text2 = (By.CSS_SELECTOR, '.page-copy > p:nth-child(2)')
    Link2Text3 = (By.CSS_SELECTOR, 'p:nth-child(5)')
    Link2Text4 = (By.CSS_SELECTOR, 'p:nth-child(7)')
    Link2Text5 = (By.CSS_SELECTOR, 'p:nth-child(9)')
    Link2Text6 = (By.CSS_SELECTOR, 'p:nth-child(11)')
    Link3 = (By.CSS_SELECTOR, '.component:nth-child(4) .promo-image-right__text-content a')
    Link3Text1 = (By.CSS_SELECTOR, '.page-copy > p:nth-child(1)')
    Link3Text2 = (By.CSS_SELECTOR, '.page-copy > p:nth-child(3)')
    Link3Text3 = (By.CSS_SELECTOR, 'p:nth-child(5)')
    Link3Text4 = (By.CSS_SELECTOR, 'p:nth-child(7)')
    Link3Image1 = (By.CSS_SELECTOR, '.row:nth-child(3) img')


class ProductsLocators(object):
    Intro = (By.CSS_SELECTOR, '.page-intro > p')
    Conclusion = (By.CSS_SELECTOR, '.field-promotext > p')
    Image1 = (By.CSS_SELECTOR, '.component:nth-child(2) .promo-image-right__image img')
    Image2 = (By.CSS_SELECTOR, '.component:nth-child(4) img')
    Image3 = (By.CSS_SELECTOR, '.component:nth-child(6) img')
    Image4 = (By.CSS_SELECTOR, '.component:nth-child(7) img')
    Link1 = (By.LINK_TEXT, 'LEARN MORE')
    Link1Text1 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(1)')
    Link1Text2 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(2)')
    Link1Image1 = (By.CSS_SELECTOR, '.item:nth-child(1) img:nth-child(1)')
    Link1Image2 = (By.CSS_SELECTOR, '.item:nth-child(2) img:nth-child(1)')
    Link1Image3 = (By.CSS_SELECTOR, '.item:nth-child(3) img:nth-child(1)')
    Link2 = (By.CSS_SELECTOR, '.component:nth-child(3) a')
    Link2Text1 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(1)')
    Link2Text2 = (By.CSS_SELECTOR, 'p:nth-child(2)')
    Link2Image1 = (By.CSS_SELECTOR, '.row:nth-child(3) img')
    Link2Link1 = (By.LINK_TEXT, 'Click here')
    Link3 = (By.CSS_SELECTOR, '.component:nth-child(4) .promo-image-right__text-content a')
    Link3Text1 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(1)')
    Link3Text2 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(2)')
    Link3Image1 = (By.CSS_SELECTOR, '.row:nth-child(3) img')
    Link3Image2 = (By.CSS_SELECTOR, '.item:nth-child(1) img:nth-child(1)')
    Link4 = (By.CSS_SELECTOR, '.component:nth-child(5) a')
    Link4Text1 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(1)')
    Link4Text2 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(2)')
    Link4Text3 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(3)')
    Link4Text4 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(4)')
    Link4Image1 = (By.CSS_SELECTOR, '.row:nth-child(3) img')
    Link4Image2 = (By.CSS_SELECTOR, '.item:nth-child(1) img:nth-child(1)')
    ShipBuilding = (By.LINK_TEXT, 'SHIP BUILDING')
    ShipBuildingText1 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(1)')
    ShipBuildingText2 = (By.CSS_SELECTOR, 'p:nth-child(2)')
    ShipBuildingText3 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(3)')
    ShipBuildingText4 = (By.CSS_SELECTOR, 'p:nth-child(4)')
    ShipBuildingText5 = (By.CSS_SELECTOR, 'p:nth-child(5)')
    ShipBuildingText6 = (By.CSS_SELECTOR, 'tr:nth-child(2) > td:nth-child(2)')
    ShipBuildingLink = (By.LINK_TEXT, 'DETACOUPLE FOR UNITED STATES')
    DetacoupleText = (By.CSS_SELECTOR, 'textarea')
    Train = (By.LINK_TEXT, 'TRAIN')
    TrainImage1 = (By.CSS_SELECTOR, '.row:nth-child(3) > .col-6:nth-child(1) img')
    TrainImage2 = (By.CSS_SELECTOR, '.col-6:nth-child(2) img')
    TrainLink = (By.LINK_TEXT, 'RAILCLAD CREATES SPARKS')
    SparksText = (By.CSS_SELECTOR, '.page-copy')
    TruckTrailer = (By.LINK_TEXT, 'TRUCK & TRAILER')
    TTArticle = (By.LINK_TEXT, 'READ THE ARTICLE')
    TTLearnMore = (By.LINK_TEXT, 'LEARN MORE')
    LearnMoreText = (By.CSS_SELECTOR, '.page-copy > p')
    Link5 = (By.CSS_SELECTOR, '.component:nth-child(6) .promo-image-right__text-content a')
    Link5Text2 = (By.CSS_SELECTOR, 'p:nth-child(2)')
    Link5Image2 = (By.CSS_SELECTOR, '.col-12 > .row .component-content > a > img')
    Link6 = (By.CSS_SELECTOR, '.component:nth-child(7) .promo-image-left__text-content a')
    Link7 = (By.CSS_SELECTOR, '.component:nth-child(8) a')
    Link7Image2 = (By.CSS_SELECTOR, '.item:nth-child(1) img:nth-child(1)')


class IndustriesLocators(object):
    Intro = (By.CSS_SELECTOR, '.page-intro > p')
    Link1 = (By.CSS_SELECTOR, '.industries-icon-promo .field-promotext > a')
    Link2 = (By.LINK_TEXT, 'CHEMICAL & PETROCHEMICAL')
    Link3 = (By.CSS_SELECTOR, '.row:nth-child(2) > .col-12:nth-child(5) .field-promotext > a')
    Link4 = (By.CSS_SELECTOR, '.row:nth-child(2) > .col-12:nth-child(7) .field-promotext > a')
    Link5 = (By.CSS_SELECTOR, '.row:nth-child(3) > .col-12:nth-child(1) .field-promotext > a')
    Link6 = (By.LINK_TEXT, 'METALS EXTRACTION & REFINING')
    Link7 = (By.CSS_SELECTOR, '.row:nth-child(3) > .col-12:nth-child(5) .field-promotext > a')
    Link8 = (By.CSS_SELECTOR, '.row:nth-child(3) > .col-12:nth-child(7) .field-promotext > a')
    Text1 = (By.CSS_SELECTOR, '.page-intro > p')
    Text2 = (By.CSS_SELECTOR, '.field-promotext3 > p')
    Image1 = (By.LINK_TEXT, 'VESSEL HEADS & CYLINDERS')
    Image2 = (By.LINK_TEXT, 'TUBE SHEETS')
    Image3 = (By.LINK_TEXT, 'CLAD PIPE')
    Image4 = (By.LINK_TEXT, 'CLAD PLATES')
    Image5 = (By.LINK_TEXT, 'STRUCTURAL TRANSITION JOINTS')
    Image6 = (By.LINK_TEXT, 'ELECTRICAL TRANSITION JOINTS')
    TriClad = (By.LINK_TEXT, 'TriClad')


class RescourcesLocators(object):
    PubResults = (By.ID, 'spanNumberInitialPubResults')
    CladResults = (By.ID, 'spanNumberInitialPCladResults')
    Pub1 = (By.CSS_SELECTOR, '#publications li:nth-child(3) .resource-search-result__resource-name:nth-child(2)')
    Pub2 = (By.CSS_SELECTOR, 'li:nth-child(16) .field-title:nth-child(2)')
    Text1 = (By.CSS_SELECTOR, '.page-copy')
    Text2 = (By.CSS_SELECTOR, 'p:nth-child(2)')
    Clad1 = (By.CSS_SELECTOR, '#commonclad li:nth-child(1) .resource-search-result__resource-name:nth-child(3)')
    Clad2 = (By.CSS_SELECTOR, '#commonclad li:nth-child(21) .resource-search-result__resource-name:nth-child(3)')
    Pic1 = (By.CSS_SELECTOR, '.field-search-result-image > img')
    ProductResults = (By.ID, 'spanNumberInitialProductResults')
    Prod1 = (By.CSS_SELECTOR, '#products li:nth-child(3) .field-search-result-short-description')
    Prod1Link1 = (By.LINK_TEXT, 'READ THE ARTICLE')
    Prod1Link2 = (By.LINK_TEXT, 'LEARN MORE')
    ProdText1 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(1)')
    ProdText2 = (By.CSS_SELECTOR, 'p:nth-child(2)')
    ProdText3 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(3)')
    ProdText4 = (By.CSS_SELECTOR, 'p:nth-child(4)')
    ProdText5 = (By.CSS_SELECTOR, 'p:nth-child(5)')
    Prod2 = (By.CSS_SELECTOR, '#products li:nth-child(8) .field-search-result-short-description')
    ProdText = (By.CSS_SELECTOR, '.page-copy > p')
    Image1 = (By.CSS_SELECTOR, '.row:nth-child(3) img')


class AboutUsLocators(object):
    MainText1 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(1)')
    MainText2 = (By.CSS_SELECTOR, 'p:nth-child(2)')
    MainText3 = (By.CSS_SELECTOR, '.page-intro > p:nth-child(3)')
    MainText4 = (By.CSS_SELECTOR, '.component-content > .field-promotext')
    Intro = (By.CSS_SELECTOR, '.page-intro > p')
    Link1 = (By.LINK_TEXT, 'LEARN MORE')
    Link1Text1 = (By.CSS_SELECTOR, '.row:nth-child(2) > .col-md-6:nth-child(1) li:nth-child(1) > p')
    Link1Text2 = (By.CSS_SELECTOR, 'li:nth-child(4) > p')
    Link1Text3 = (By.CSS_SELECTOR, '.row:nth-child(3) > .col-md-6:nth-child(1) li:nth-child(1) > p')
    Link1Text4 = (By.CSS_SELECTOR, '.col-md-6:nth-child(2) ul:nth-child(2) p')
    Link2 = (By.LINK_TEXT, 'CONTACT US')
    Link2Text1 = (By.CSS_SELECTOR, 'li:nth-child(1) .office-location-results__address')
    Link2Text2 = (By.CSS_SELECTOR, 'li:nth-child(8) .office-location-results__address')
    Link3 = (By.CSS_SELECTOR, '.component:nth-child(4) .promo-image-right__text-content a')
    Link3Text1 = (By.CSS_SELECTOR, '.row:nth-child(3) > .col-12:nth-child(1) .promo-body')
    Link3Text2 = (By.CSS_SELECTOR, '.row:nth-child(4) > .col-12:nth-child(1) .promo-body')
    Link3Text3 = (By.CSS_SELECTOR, '.col-md-6 > .field-promotext2')
    Link4 = (By.LINK_TEXT, 'JOIN US')

